# Generated by Django 4.0.4 on 2022-04-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, verbose_name='Name')),
                ('LastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('Jobs', models.CharField(choices=[(0, 'COUNTER'), (1, 'ADMINISTRATOR'), (2, 'Economist'), (3, 'Others')], max_length=1, verbose_name='Jobs')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Departamento', to='departamento.departamento')),
            ],
        ),
    ]
