# Generated by Django 4.0.4 on 2022-05-01 05:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Habilidades', models.CharField(max_length=50, verbose_name='Habilidades')),
            ],
            options={
                'verbose_name': 'Habilidades',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, verbose_name='Name')),
                ('LastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('Jobs', models.CharField(choices=[('0', 'COUNTER'), ('1', 'ADMINISTRATOR'), ('2', 'Economist'), ('3', 'Others')], max_length=1, verbose_name='Jobs')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='empleado')),
                ('resume', ckeditor.fields.RichTextField()),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Departamento', to='departamento.departamento')),
                ('habilidades', models.ManyToManyField(to='persona.habilidades')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persona',
                'ordering': ('-FirstName',),
                'unique_together': {('FirstName', 'LastName')},
            },
        ),
    ]
