# Generated by Django 4.0.4 on 2022-04-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='Jobs',
            field=models.CharField(choices=[('0', 'COUNTER'), ('1', 'ADMINISTRATOR'), ('2', 'Economist'), ('3', 'Others')], max_length=1, verbose_name='Jobs'),
        ),
    ]
