# Generated by Django 4.0.4 on 2022-04-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Habilidades', models.CharField(max_length=50, verbose_name='Habilidades')),
            ],
            options={
                'verbose_name': 'Habilidades',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('-FirstName',), 'verbose_name': 'Persona', 'verbose_name_plural': 'Persona'},
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('FirstName', 'LastName')},
        ),
    ]
