# Generated by Django 4.0.4 on 2022-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_habilidades_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='habilidades',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
    ]
