# Generated by Django 4.0.4 on 2022-04-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_persona_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Full Name'),
        ),
    ]
