# Generated by Django 4.0.4 on 2022-04-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_persona_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado/%Y/%m/%d'),
        ),
    ]
